<%@ Page Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="TweeBuck.aspx.cs" Inherits="TweebaaWebApp.College.TweeBuck" %>

<asp:Content ID="Content1" ContentPlaceHolderID="WebTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="WebCssAndJs" runat="server">
    <link rel="stylesheet" href="../css/college-new.css" />
    <link rel="stylesheet" href="../css/selectCss.css" />
    <script src="../js/jquery.min.js" type="text/javascript"></script>
    <script src="../js/jquery.placeholder.js" type="text/javascript"></script>
    <script src="../js/reg.js" type="text/javascript"></script>
    <script type="text/javascript" src="../js/jquery-hcheckbox.js"></script>
    <script type="text/javascript" src="../js/jquery.xScroller.js"></script>
    <script type="text/javascript" src="../js/dragbox.js"></script>
    <script type="text/javascript" src="../js/public.js"></script>
    <script src="../js/custom.js"></script>
    <script type="text/javascript" src="../js/script.js"></script>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="WebContent" runat="server">
<div class="w975 mbx">
		<a href="/index.aspx">Homepage</a> > <a href="/College/College.aspx">Education</a> > <b class="l">GENERAL TERMS OF SERVICE FOR TWEEBAA</b>
	</div>
<div class="ctitle"><ul>
<li class="p1">TERMS OF SERVICE FOR TWEEBUCK ACTIVITIES</li>
<li class="line"></li></ul>
<div class="w975">
<li class="p3">These terms of service for TweeBuck Activities form part of your General Terms of Service with Tweebaa (as defined therein, the <strong>“Agreement”</strong>). These terms and conditions are supplemented by the chart setting out commission levels available per Zone Level (the <a href="/College/Commission-chart.html"> “Commission Chart”</a>) and the chart setting out reward points available for particular TweeBuck Activities (the<a href="/College/ZoneRewardPoints.aspx?page=Zone-reward-points"> “Reward Point Chart”</a>). Terms starting with capital letters or defined in the Tweebaa General Terms of Service have the same meaning as the <a href="/College/Genernal_Terms_ofUse.aspx" target="_blank"> General Terms of Service</a>
<br /><br />
<strong>By accessing or using the Service, you signify that you have read, understand and agree to be bound by this Agreement in all respects with respect to the Website, our provision of the Service, and your use of them.<br /><br />
PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE, BUT ARE NOT LIMITED TO, VARIOUS LIMITATIONS AND EXCLUSIONS, AND INDEMNITIES.

</strong>
 </li>
 <ul> <li class="p10"> <strong>TweeBuck Activities;</strong>  Amendments. You may use our Services to receive compensation pursuant to the terms of the Agreement by engaging in certain qualified activities that we may, under the terms of this Agreement, determine meet certain thresholds and requirements to be considered a <strong>“TweeBuck Activity”</strong>. We reserve the right, at our sole discretion to change, modify, add or delete portions of these TweeBuck Activity Terms of Service as set out in Section 1 of the General terms of Service. </li><br />

 
 
 <li class="p10"><strong>	Product Submission. </strong>You acknowledge you have read, understand, and are responsible for following the <a href="/College/SubmitZone.aspx?page=submit-zone">Submit Zone education section </a>and rules which we may change, alter, modify, add to, or delete from time to time in our sole discretion, concerning your ability to submit (<strong>“Submit”</strong>) a consumer product (<strong>“Product”</strong>) to us for evaluation, review, and the chance of being selected to be offered for sale in the Tweebaa Shop. You must have a Tweebaa User Account in order to Submit a Product. There is no limit on the number of Products you may Submit, however, you acknowledge and agree that we reserve the right (but we have no obligation), in our sole discretion, to reject any Submission without explanation or notice, which includes our ability to reject duplicative or similar Products. By Submitting a Product, you signify that you understand and acknowledge that we in no way guarantee that we will accept or review the Product you Submitted or that your Submission could lead to activities that may be considered a TweeBuck Activity in the future. You further understand and acknowledge that a Submitted Product must successfully pass through three stages, being Evaluation (where a Product must receive a number favourable Evaluations as we determine in our sole discretion from time to time), Tweebaa Review (where we will review the product against Tweebaa criteria in our sole discretion) and Test-Sale (where the Product must meet a target sale quantity in a target time period), before we may consider including the product in the Tweebaa Shop. You understand and agree that we have no obligation to independently review the Product or Content and that we will not verify, guarantee, or assume any responsibility or liability for, the accuracy, completeness, efficacy, or timeliness of any Content.</li><br />

<ul>
<li class="p11">You represent and warrant that any Product ready for commercial sale you Submit for consideration is a tangible good and is not an unproven invention or a concept, business idea, service, investment opportunity, or method of doing business. You further represent and warrant that any Product you Submit: 
<ul>
<li class="p16">is likely to be commercially available in the areas to which we may sell the Product, </li>
<li class="p16">is not an item identified as hazardous to consumers by a consumer product safety commission in any jurisdiction to which we may sell the Product, and</li>
<li class="p16">is not a Product considered to be a infant or baby item, furniture, supplement, vitamin, medical product or device (other than for household use), weapon, pharmaceutical, drug, or real estate. </li>

</ul></li>
<li class="p11">You further represent and warrant that the Content you upload with your Submission:
<ul>
<li class="p16">complies with all terms provided in the Submit Zone and in this Agreement, </li>
<li class="p16">	to your knowledge complies with applicable consumer product legislation in your jurisdiction, </li>
<li class="p16">does not host Content unrelated to the Product Submitted,</li>
<li class="p16">	does not suggest in any way, whether express or implied, that your Content or the Product is endorsed, approved, or sponsored by us in any way,  </li>
<li class="p16">	is a true, fair, accurate, and good faith representation of the Product and contains all disclosures and disclaimers necessary to prevent such Content from being false or deceptive, </li>
<li class="p16">does not inflate, overstate, amplify, aggrandize, exaggerate, embellish, hyperbolize, overestimate, dramatize, misstate, confuse, distort, or misrepresent the Product or have the likely effect of misleading a consumer, or making any false or misleading representation, with regards to the Product’s qualities, use, effects, size, or condition of the Product Submitted,</li>
<li class="p16">to the extent the Content includes testimonials, endorsements, or approvals of a Product, whether implicit or explicit, it complies with all applicable laws and regulations, and</li>

<li class="p16">makes no claims or comparisons whatsoever, express or implied, with regard to health, or medical benefits or treatment, or medical effects of a Product.</li>

</ul></li>
<li class="p11">You agree that though you may suggest a price for a Product you Submitted, we will set the price and may change the price in our sole discretion without notice to you or other Users.
</li>
</ul><br />
 <li class="p10"> <strong>Product Evaluation. </strong> You acknowledge you have read, understand, and are responsible for following the Evaluation Zone education section and rules concerning your ability to evaluate a Product (an “Evaluation”), which we may change, alter, modify, add to, or delete from time to time in our sole discretion. You agree to Evaluate Products in good faith and without any inappropriate, malicious, or threatening language.  You must have a Tweebaa User Account in order to Evaluate a Product. You may not Evaluate a Product that you have Submitted. Each User may Evaluate up to ten Products in the Evaluation Zone per 24 hour period. Any Evaluations completed beyond 10 in each 24 hour period will not be considered towards the success or failure of the Product and will not be considered a TweeBucks Activity. Only completed Evaluations may be considered a TweeBuck Activity. An Evaluation is completed only if you are logged in to your Tweebaa User Account, you answer all questions provided in the survey, and your Evaluation complies with the terms of this Agreement. We reserve the right, in our sole discretion to determine whether an Evaluation has been completed. In addition:</li>
 <ul>
<li class="p11"><strong>Accurate Evaluations.</strong> You acknowledge that you may receive an additional Reward Point if your Evaluation is accurate in determining whether the Product will advance to the Tweebaa Shop. You also acknowledge that you may  lose a Reward Point if your Evaluation is inaccurate. Whether an Evaluation is accurate will be determined by the answer and result to a question in the survey asking whether you believe the Product will advance to the Tweebaa Shop.  The wording of this question and whether the response is accurate will be determined in our sole discretion and may be changed, modified, or amended at any time by us without notice to any User. </li>
<li class="p11"><strong>No Endorsement.</strong> All Content you provide in your Evaluation represents your own opinions and does not reflect the opinions of the Tweebaa Companies. We reserve the right to moderate any Evaluations but have no obligation to do so. We further reserve the right to determine in our sole discretion whether your Evaluation will be considered a TweeBuck Activity.  </li>
<li class="p11"><strong>No Sock Puppetry.</strong> You acknowledge and agree that you may not engage in any deceptive activity to increase the Evaluations on your Product, including creating additional Tweebaa User Accounts, using another’s Tweebaa User Account, reviving an old Tweebaa User Account and presenting it as a unique user, coordinating, compensating, or improperly persuading others to Evaluate Products you have Submitted.</li>
 <br />
  <li class="p10"> <strong>Product Sharing.</strong>  You acknowledge you have read, understand, and are responsible for following the Share Zone education section and rules concerning your ability to share (<strong>“Share”</strong> ) a Product available on Tweebaa, which we may change, alter, modify, add to, or delete from time to time in our sole discretion. There is no requirement to be logged in to your Tweebaa User Account to Share a Product, but you must be logged in to your Tweebaa User Account and click the “Share and Earn” button to receive a customized link so that your Share will be considered a TweeBuck Acticity. There is no limit on the number of Products you may Share or amount of times you may Share a Product. There are at many ways to Share a Product with your friends or contacts, including Sharing a Product offered for sale by us in the Tweebaa Shop with your friends and contacts by emailing the generated link to the Product or posting the link on a social media website (<strong>“One-Click Sharing”</strong> ) and sharing a Product you purchased with friends and contacts (<strong>“Purchase Sharing”</strong> ). You agree not to Share a Product with any person where it would be illegal or contrary to applicable regulation to do so, including in the United States to any person under the age of 13 and in other jurisdictions, to a person under the age of majority in that jurisdiction. By sharing any Content regarding the Product in addition to the generated link, you hereby represent and warrant that you have complied with all terms provided in this Agreement. Each Product in the Tweebaa Shop may be Shared through its Share & Earn button.  Only completed Shares may be considered a TweeBuck Activity. A Share is successfully completed only if:
     <ul>
<li class="p11">	a person with whom you have Shared a Product, clicks on the link from a unique and identifiable IP address, and</li>
<li class="p11">	a purchase is made through your Shared link and the Product is neither returned nor refunded, or </li>
<li class="p11">	 new Tweebaa member registers for a Tweebaa User Account from your Shared Link.</li>

</ul>
If a Product does not pass the Test-Sale, any Purchase of that Test Sale Product will not be considered completed for the purposes of TweeBucks Activities. You acknowledge that in order to track your Sharing Activity, we may be required to collect and monitor information from other websites (<strong>“Third Party Sites”</strong> ) on which you Share the Product. We reserve to right to monitor your Sharing but not the obligation to do so. You covenant and agree to comply with all applicable law when Sharing a Product, including (i) compliance with the terms of use or service of all Third Party Sites and (ii) compliance with Canada’s Anti Spam Law (<strong>“CASL”</strong> ) and all applicable anti spam legislation in any jurisdiction in which the recipient with whom you may Share a Product resides. 
  </li>
<br />
   <li class="p10"> <strong>	Rewards Points.  </strong>	We determine the level of compensation you may receive from us in a tiered compensation scheme based on the number of points (<strong>“Reward Points” </strong>	) you have accumulated by successfully completing certain TweeBuck Activities. You agree that you have no right or reasonable expectation to receive Reward Points and that we, in our sole discretion, may determine the calculation of Reward Points. We also reserve the right to deduct Reward Points from your Tweebaa User Account if we determine, in our sole discretion, that you have incorrectly predicted an Evaluation or have failed to abide by this Agreement. If applicable, we may assign the Reward Points you may receive to one of the three zones (<strong>each a “Zone” </strong>	), being the Submit Zone, Evaluate Zone, and Share Zone. You acknowledge and agree that Reward Points accrued in one Zone may not be transferred to another Zone. You further agree that Reward Points are personal to you and are non-transferable to another User. Reward Points have no value. You acknowledge and agree that you must be logged in to your Tweebaa User Account while you are engaged in the TweeBuck Activity to receive or redeem Reward Points. Any Reward Points you receive will be automatically applied to your Tweebaa User Account. You agree that any Reward Points you may have otherwise received may be forfeited in you are not logged in to your Tweebaa User Account. We reserve the right to deduct Reward Points from your Tweebaa User Account if the TweeBuck Activity ended in a return or refund of the Product. You may view your current Reward Points and Level in each Zone by logging into your Tweebaa User Account at <a href="/User/login.aspx" >Login Page</a>. </a>You agree that the number of Reward Points you may receive will be provided in the Reward Points Chart. We reserve the right to modify, add, change, or delete the Reward Points Chart in our sole discretion and without notice by posting the updated Commission Chart at  <a href="/College/Commission-chart.html" > Commission chart page</a>. It is your responsibility to regularly check this page to determine if there have been changes to Commission Chart and to review such changes.</li>   
<br />
   <li class="p10"> <strong>	Nudity and Objectionable Material.</strong>  You acknowledge and agree that the Service must remain a safe site for families with children, so you agree not to, and we strictly prohibit, the uploading and display of any User Content portraying explicit nudity, adult content, or that is unacceptable for viewing by minors or objectionable, in our sole discretion. For example, but without limitation, prohibited User Content would include material that would be unacceptable in a public museum where minors visit, or User Content that would only be appropriate for adult sites, adult magazines, or R-rated movies. You acknowledge and agree that the sole discretion of whether User Content is suitable belongs to us, and we reserve the right (but have no obligation) to (a) delete any User Content we deem to violate this Agreement or, or (b) to cancel the Tweebaa User Account from which such User Content made available on the Service.</li>
      <ul>
<li class="p11"><strong>Submit Zone.</strong> You may receive Reward Points to accrue in the Submit Zone based on submissions or if we have approved, in our sole discretion, one or more Product you have Submitted for Test-Sale or sale in the Tweebaa Shop as set out in the <a href="/College/SubmitZone.aspx?page=submit-zone" > Submit Zone education section.</a></li>
<li class="p11"><strong>Evaluate Zone. </strong>You may receive Reward Points for each completed and submitted Evaluation of another User’s Product, up to a maximum of 10 Evaluations per day. You will not receive any Reward Points for an Evaluation of a Product you have Submitted. You may receive Reward Points for every successful Evaluation you complete and submit. An Evaluation is successful if, from the date you complete the Evaluation, you correctly predicted whether the Product would pass the Evaluation stage within 30 days. You acknowledge and agree that we will deduct Reward Points for each inaccurate Evaluation. An Evaluation is inaccurate if, from the date you complete the Evaluation, you incorrectly predicted whether the Product would pass the Evaluation Stage within 30 days.</li>
<li class="p11"><strong>Share Zone.  </strong>We will provide you with a link to Share a product. To receive Reward Points in the Share Zone, you must Share the official Share Link that we have provided to you. You agree not to modify any Links or tracking data. You may receive Reward Points for clicks and purchases from a unique IP address on a Product that you have Shared. </li>
<li class="p11"><strong>Referral Reward Points. </strong> You may receive Reward Points for referring us to a new member who successfully registers and creates a Tweebaa User Account. There are two ways to refer a member from which you may receive Reward Points: 1) when your referral registers for a Tweebaa User Account, your referral must select that they were referred by a friend and list the email address associated with your Tweebaa User Account in the available box of the registration form; or 2) your referral’s registration for a Tweebaa User Account originated with the link you Shared. Reward Points received for referrals, if any, will be applied equally to all three Zones within your Tweebaa User Account. We may, but are not required to, provide you with additional Shopping Reward Points for each new member’s Tweebaa User Account created as a result of your referral. </li>
<li class="p11"><strong>Shopping Reward Points.  </strong>You may receive one Reward Point for every [US] dollar you spend purchasing (excluding shipping fees and taxes) roduct from the Tweebaa Shop (“Shopping Reward Points”). You may further receive Shopping Reward Points for browsing in the Tweebaa Shop. To earn Shopping Reward Points for browsing, you understand that you must open a minimum of ten Products in the Tweebaa Shop per 24 hour period by opening the product detail page and clicking on the “Browse and Earn” button. If you do not click on the “Browse and Earn” button in the product detail page of at least 10 products per day, you will not receive any Shopping Reward Points for browsing for that day. You acknowledge and agree that Shopping Reward Points expire within six months from the date received. Once Shopping Reward Points Expire, we will delete these Reward Points from your Tweebaa User Account. </li>
<li class="p11"><strong>Check In Reward Points.  </strong>You may receive additional Reward Points for each day you check in to your Tweebaa User Account and click “Daily Check In”. Check In Rewards received for daily check ins, if any, will be applied equally to all three Zones within your Tweebaa User Account.</li>
<li class="p11"><strong>Redeeming Reward Points. </strong> You agree that Reward Points may not be exchanged for cash, gifts, or coupons. You may apply some or all of your Shopping Reward Points to your purchase amount for your purchase of Products in the Tweebaa Shop. You acknowledge and agree that the redemption value applied for any number of Reward Points will be listed in the Compensation Chart. Any discounts available from the application of Reward Points, if any, will be determined by us in our sole discretion.</li>
</ul><br />
  <li class="p10"> <strong>Commissions.  </strong>The number of Reward Points you may receive in each Zone will delineate the compensation tier (“Level”) at which we will apply any commission (“Commission”) you may receive for successfully completing a TweeBucks Activity. Please see the Commission Chart for a current listing of the amount of Commission which may be available at each Level.  Commissions are calculated based on our tracking data, which is deemed definitive and shall control in the event of any commission dispute. The Commission will be based on a percentage rate of the price of the Product at the respective date as set out herein, less any discounts and does not include any shipping fees or taxes. We reserve the right to modify, add, change, or delete the Commission Chart, any Commission rates or percentages, and any compensation related thereto in our sole discretion and without notice by posting the updated Commission Chart at www.tweebaa.com/College/Commission-chart.html. It is your responsibility to regularly check this page to determine if there have been changes to Commission Chart and to review such changes. You acknowledge and agree that you will not receive Commissions for any action that we do not consider, in our sole discretion, to be a TweeBuck Activity.</li>

 <ul>
<li class="p11"><strong>Receiving Commissions.</strong> You agree that the Commission ratio for any Commission you may receive is based upon your Zone Level at the time of your Submission, Evaluation, or Sharing (and is fixed for the relevant activity at such time notwithstanding changes to your Zone Level at a later time). Any Commission you receive for the Submission of a Product will accrue only for Products successfully sold in the Tweebaa Shop and will be terminated on the date we remove the Product from the Tweebaa Shop. With the exception of sharing, no Commission is provided for any Test-Sale Products sold. We reserve the right to make a change to the price a Product is sold by discount, sale or otherwise, which you acknowledge may affect any Commission available on the Product. You may receive a Commission in the following situations:   
<ul>
<li class="p16">if a Product that you Submit is sold in the Tweebaa Shop, you may receive a Commission according to your Submit Zone Level at the time you Submitted the Product,</li>
<li class="p16">if a Product that you successfully Evaluated is sold in the Tweebaa Shop and we select you (in our sole discretion) as an Evaluator, you may receive a Commission according to your Evaluation Zone Level at the time you Submitted the Product,</li>
<li class="p16">if a Product is successfully sold in the Tweebaa Shop and such sale originated with the link you Shared, you may receive a Commission on the Purchase according to your Share Zone Level at the time the Product is Purchased. You will not receive a Commission on any Product sold if it was returned or the subject of a Chargeback, in which case the TweeBuck may be listed as “pending” until it is “available”. </li>

</ul></li>
<li class="p11"><strong>Redeeming Commissions.</strong>  The Commission you receive, if any, will be posted to your Tweebaa User Account as TweeBucks when accrued per the terms herein and may only be redeemed if and when we have removed a notification that the Commission is “pending” from and have applied the “available” notification to your Tweebaa Account. Your agree that the Commission posted to your Tweebaa User Account, if any, is only in TweeBucks and is not redeemable directly for cash, coupons or gifts, except as set out in Section 8. </li>

</ul>
<br />
<li class="p10"><strong>TweeBucks.</strong>  TweeBucks represent the compensation you may receive as your Commission under the terms and conditions provided in this Agreement. TweeBucks are non-transferrable and have no cash value outside of their use towards your purchase of a Product in the Tweebaa Shop or once redeemed for cash as provided herein. TweeBucks have no expiration date; however,  you agree TweeBucks are forfeited if your account is deleted or deactivated for any reason.</li>

 <ul>
<li class="p11"><strong>Redeeming TweeBucks. </strong> TweeBucks may be redeemed for cash or applied to your purchase of a Product from the Tweebaa Shop. TweeBucks will be redeemed at the rate listed in US dollars (the <strong>“Redemption Rate”</strong>) provided in the Commission Chart. A minimum redemption value of US$10.00 (the <strong>“Redemption Threshold”</strong>) is required before you may redeem any or all of your TweeBucks in cash. TweeBucks may be applied to your purchase of a Product in the TweeBucks Shop at any time without a threshold. Further, you agree that TweeBucks are not redeemable if and as long as they are listed as<strong> “pending” </strong>in your Tweebaa User Account. You may only redeem TweeBucks once they are listed as <strong>“available” </strong>in your Tweebaa User Account. Once you have reached the Redemption Threshold, you may redeem your TweeBucks for cash from your Tweebaa User Account through your registered PayPal (<strong>“PayPal”</strong>) Account. You agree that to receive a transfer, you must ensure that your PayPal account is set up with the ability to receive payments from third parties. You may redeem your TweeBucks for cash a maximum of one time per week, provided your TweeBucks are above the redemption Threshhold prior to each redemption. The minimum withdrawal amount for a cash redemption is the Redemption Threshold. </li>
<li class="p11"><strong>Redemption Method.</strong> You can collect your redeemed TweeBucks with a verified PayPal Account. You agree that PayPal is the sole method of payment we offer. All amounts are applied to your PayPal Account in your default currency and at the exchange rate provided for in your agreement with PayPal. You hereby understand and agree that PayPal is the only method through which you may redeem your TweeBucks for cash and agree that we are under no obligation to provide a cash value to you for any TweeBucks through any method other than PayPal. You agree that your TweeBucks will be redeemed for cash in the currency you have set as your default currency in PayPal. We reserve the right to deduct transaction charges from PayPal related to your withdrawals from your TweeBuck balance in your Tweebaa User Account. You further agree that we have no responsibility or obligation to you with respect to your PayPal Account.  You understand that PayPal is a Third Party Site and falls within all terms applying to Third Party Sites in this Agreement. You hereby agree and covenant to resolve any disputes with your PayPal Account by the terms and conditions provided in your agreement with PayPal. </li>
</ul>

<br />
<li class="p10"><strong>No Relationship. </strong>You hereby acknowledge and agree that no employment, joint venture, partnership, or agency relationship exists between you and any of the Tweebaa Companies as a result of this Agreement or your use of our Services.  We are solely independent contractors.</li>
<br />
<li class="p10"><strong>Requirement to Withhold Taxes.  </strong>  We do not collect or remit any taxes for any Commission or Reward Point received in any jurisdiction. You acknowledge and agree that in connection with your use of our Service, you may be required to comply with income tax and withholding requirements on any income you receive and that if such an obligation arises you will be solely responsible for the timely payment of such tax and any interest or penalties. The payment rate used for computing Commission paid to you is inclusive of any and all applicable federal, provincial, state, local, or other fees or taxes owed by you. In no cases will any additional compensation be paid to you for taxes. You hereby covenant and agree to remit all required taxes that you owe or may owe in connection with TweeBucks Activities and to pay all tax obligations therefrom in a timely manner. If we, in our sole discretion, determine we are required to withhold any taxes in connection with your Commission, we may but are under no obligation to do so. You acknowledge and agree that you are solely responsible for all tax compliance relating to your use of our Service and that in no event will we be responsible for any tax compliance. If it is later determined that we should have withheld and/or paid tax but did not withhold or pay such tax, then you shall repay to us the applicable tax as requested by us and hold us harmless from any penalties or interest thereon. You further agree to indemnify and hold the Tweebaa Companies and each of their directors, officers, agents, contractors, partners and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney's fees, arising out of or in connection with any claims by the Canada Revenue Agency or any taxes related to your use of the Service.  </li>
<br />
<li class="p10"><strong> No Guarantee. </strong> 	 We make no guarantee regarding any Product sales, Evaluations, the level of Reward Points or Commission, clicks, referrals, Shares, or events that may generate  TweeBucks, the timing of such sales, Evaluations, Shares, clicks, conversion events, or the amounts of any Commissions, Reward Points, or TweeBucks to be attributed to you, or payments to be made to you under this Agreement. We reserve the right to use our sole discretion in determining instances of incomplete, invalid, or unsuccessful Sales, Evaluations, Shares, referrals, clicks, or TweeBuck Activity. You agree that we reserve the right, but are not obliged, to use fraud detection systems. We may, in our sole discretion, offer discounts to Users who purchase Products through Shared links. You understand and acknowledge that any change or modification we make in our sole discretion to the price of a Product may affect the Commission available on such Product.</li>
<br />
<li class="p10"><strong>	Non-Payment. </strong> Nowithstanding anything to the contrary herein, we will have no duty to compensate you for a TweeBuck Activity that would otherwise result in Reward Points, Commission, or TweeBucks, during any period in which you were or are in breach of this Agreement. We further reserve the right to withhold compensation for any and all previous periods and for any Commission you are accruing if we, in our sole, discretion, have reason to believe that you have breached this Agreement or have engaged in potentially fraudulent activities.</li>
<br />
<li class="p10"><strong>Returned Sales. </strong> Consumers may return Products pursuant to our [Return and Refund Policy] [Link]. TweeBucks received from a TweeBuck Activity will remain listed as “pending” in your Tweebaa User Account until the Return Period has passed. If a Product is returned within the relevant return period, any Reward Points or Commission received will be removed from your Tweebaa User Account. </li>
<br />
<li class="p10"><strong>	Charged Back Sales. </strong> If a customer successfully disputes a charge for the purchase of a Product through their bank or credit provider (a<strong> “Chargeback”</strong>), the Reward Points or Commission receiveed through the Chargeback Purchase will be deducted from your Tweebaa User Account. If your Tweebaa User Account has a negative balance or a balance of zero, the points will still be deducted, resulting in a debit in your Tweebaa User Account. We may apply a debit of TweeBucks to your Tweebaa User Account at any time due to a Chargeback. 
15.	Account Closure.  You may delet </li>
<br />
<li class="p10"><strong>Account Closure. </strong> You may delete your Tweebaa User Account at any time. If you delete your Tweebaa User Account, we may, in our discretion, make commercially reasonable efforts to transfer any “available” closing balance, less debits, to your PayPal Account, to automatically redeem any amount over $10 to your last known PayPal Account. You acknowledge that if, after reasonable efforts to transfer or redeem your balance, we are unable to do so, you forfeit all of your closing balance, if any, remaining in your Tweebaa User Account. </li>
<br />
<li class="p10"><strong>Disclaimers. </strong> You acknowledge and agree that Sections 18 and 19 of the General Terms of Service apply fully, to the extent they are relevant, to TweeBuck Activities and Commissions.
<br /><br />
End of Terms of Service (Last Updated: 06/06/2015)<br /><br />
</li></div>


</div>
      
        </div>
      </div>
<div class="ebtn clearfix">
<ul><li > <a href="/College/College.aspx" class="bli" >Back to Education home page</a></li></ul></div>
</asp:Content>