<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="supplyAgreement.aspx.cs" Inherits="TweebaaWebApp.Product.supplyAgreement" %>
<asp:Content ID="Content1" ContentPlaceHolderID="WebTitle" runat="server">
PRODUCT SUPPLY AGREEMENT
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="WebCssAndJs" runat="server">	
	<link rel="stylesheet" href="css/index.css" />
	<link rel="stylesheet" href="css/selectCss.css" />
    <script src="http://code.jquery.com/jquery-1.7.2.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/public.js"></script>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="WebContent" runat="server">


<div class="sub-wel-main">
<!-- 发布协议弹出框 -->
<div class="w clearfix">
	<div class="tck-gh">
		<div class="pr">
			<h5><strong>PRODUCT SUPPLY AGREEMENT</strong></h5>
			<div class="scr_con2">
				<div id="dv_scroll2">
					<div id="dv_scroll_text" class="Scroller-Container2">
						<div class="tcCon" id="tcCon">
                        <p style="font-weight:bold; font-size:14px;">This Product Supply Agreement (the "Agreement") will govern the relationship between Tweebaa, Inc USA ("Tweebaa") and the Partner identified in this document ("Supplier"). This Agreement constitutes the final, complete, and exclusive statement of the Agreement of the Parties with respect to the subject matter hereof, and supersedes any and all other prior and contemporaneous agreements and understandings, both written and oral, between the Parties.<br />Both parties hereby agree as follows:</p>
						
								
<h6>1.Term.</h6>
 	<p>This Agreement shall be effective as of the Effective Date and continue for a period of Twelve (12) months (the "Term"). Unless otherwise terminated hereof, this Agreement shall renew automatically at the end of the Term for additional and successive 1 year periods, unless either Party gives written notice of termination at least 45 days before the end of the Term or any renewal term.<br /></p>
<h6>2.	Sale of Product.</h6>
 	<p>The Seller agrees and acknowledges that Tweebaa will list, market, and sell the Product ("Product") submitted by the Supplier through the <a href="#"  style="color:#1D3A88" >www.Tweebaa.com</a> website, applications, and other channels including but not limited to emails, affiliates, electronic promotions, and/or assignees and partners. Seller agrees not to circumnavigate the website or manipulate any feature or use offered by the Tweebaa website in order to eliminate or diminish product sales. All leads and sales generated by Tweebaa shall belong to Tweebaa, and by no means can the Seller exclude Tweebaa from any future transactions if the first point of contact with the lead was via Tweebaa and/or its website.<br /></p>
    <h6>3.	Nonexclusive Order.</h6>
 	<p>This is not an exclusive agreement. Tweebaa is free to engage other suppliers of which may carry similar products, and the Supplier is free to sell their Product through other channels.<br /></p>
<h6>4.	Pricing.</h6>
 	<p>The Supplier shall supply the Products to Tweebaa at the prices specified in the Supplier Form, which will be made a part hereof. Tweebaa will not be charged for insurance or storage of the Products. If at any time the Supplier reduces the price of said Product(s) Supplier will immediately adjust its pricing charged to Tweebaa and issue a credit of equal value for the difference thereof, while honoring the initial margin or percentage previously agreed on by both parties. <br /></p>
<h6>5.	Delivery of Products.</h6>
 	<p>The Supplier shall deliver the Products to a location instructed by Tweebaa (the "Delivery Point") within 2 days of receipt of a Purchase Order. The Supplier assumes all responsibility for the Product(s), and all risk of damage, loss, or delay of the Products, until the Products are delivered at the Delivery Point specified by Tweebaa. Once the Products are at the Delivery Point, Tweebaa assumes all responsibility for and risk of damage to such Products. However, if the Product is damaged in transit the Supplier will be responsible for damages. <br /></p>
							
<h6>6.	Product Changes.</h6>
 	<p>During the Term that any of the Agreements are in effect, Supplier shall not make any changes in the design, material, process, procedures or practices affecting Product to be furnished by Supplier without first notifying Tweebaa in writing. If design or manufacturing details of Product should change at any time, the Supplier must notify Tweebaa as soon as possible and before fulfilling any Purchase Orders. <br /></p>
    
    <h6>7.	Shipping and Fee's.</h6>
   
 	<p>Supplier will ship the Product as instructed by Tweebaa within two (2) business days after receiving the order(s) and instructions from Tweebaa, unless otherwise specified through the agreement or special request by Tweebaa.  The Supplier will not charge Tweebaa a dropship, handling or any other fee beyond the prices agreed upon.</h6>

    <h6>8.	Audit and Inspection.</h6>
 	<p>Any Product(s) found to be unwarranted, damaged, or otherwise unacceptable according to the terms and conditions set herewithin or otherwise implied, Supplier shall, at Tweebaa's or Tweebaa's customer's option, refund to Tweebaa the amount paid for the Product or replace the Product at no expense to Tweebaa or any of its customers. Tweebaa may request the customer ship faulty Product to Tweebaa or the Supplier for audit and inspection. The cost of inspection, storage, transportation, repacking, or reinspection by Tweebaa or any customer shall be solely at the expense of the Supplier.<br /></p>
    
    
    <h6>9.	Payment and Terms.</h6>
 	<p>Supplier will provide an invoice for the Product(s) identified in this Agreement and according to the agreed pricing in the Supplier Form which includes all applicable taxes.  Tweebaa will pay Supplier net 30 days from the receipt of invoice. If Supplier is unable to fulfill its obligations under this Agreement for any reason, including, but not limited to inventory shortage, failure to obtain and/or ship and deliver any of the Product as set forth in this Agreement within the time frame set forth therein, and Supplier does not notify Tweebaa of expected or potential delays, Supplier will remit to Tweebaa, for each affected Good, ten dollars ($10.00). If Supplier notifies Tweebaa about any issues or potential delays in advance, Tweebaa will make its best effort to remediate the issue with the Supplier.  
<br /></p>
    
    <h6>10.	License.</h6>
 	<p>Supplier hereby allows and acknowledges Tweebaa the rights and privileges to display, use, advertise, edit, license, and reproduce Supplier's name, logo, and trademarks, and any photographs, graphics, artwork, text, and other content provided or specified by Supplier (collectively, "Supplier IP"). In no way or form shall Tweebaa be liable to Supplier or its Subcontractors, affiliates, or photographers for copyright infringement of any material collected or used in association with said Product(s) or Supplier IP.<br /></p>
    
    
        <h6>11.	Confidentiality.</h6>
 	<p>Supplier shall not, either directly or indirectly, in whole or in part, use or disclose to any person, firm, corporation, or other entity, any of Tweebaa'a confidential information, which may include (but not be limited to) records, customer lists, data, formula, documents, drawings, inventions, methods, or processes. Information about the Products that is revealed during the Term is confidential and shall be protected from disclosure. Shall this contract or any related contract to the Parties be canceled, void, or expired, and/or upon written request from Tweebaa, Supplier agrees to shred, destroy and delete all confidential information and correspondence by and between Tweebaa and Supplier.<br /></p>
    
        <h6>12.	Intellectual Property.</h6>
 	<p>Supplier acknowledges and agrees that, as between the parties and according to this agreement, Tweebaa owns all rights, title, and interest in any and all customer data, website content, Tweebaa trademarks, copyrights, and any and all other information, materials, software, technology, or methods used by Tweebaa to promote and/or resell the Product (collectively "Tweebaa IP"). Supplier and Suppliers Subcontractors may not access, use, replicate, or authorize use of any Tweebaa data, customer information, or any personally identifiable information without express written permission for Tweebaa.<br /></p>
    
        <h6>13.	Warranties.</h6>
 	<p>The Supplier warrants that the Products supplied shall be free from defects in material and manufacture, conform to specifications set forth in Supplier Form, and conform to specifications set forth in any Purchase Order at the time of shipment. Supplier hereby agrees and warrants that all Product(s) are genuine, bona fide, and in conformity with all Federal, State, and Local laws, unless otherwise explicitly stated herewithin. Supplier represents and warrants that Product(s) are in accordance with all written instructions, specifications, and within the compliance of this Agreement. Product(s) shall be manufactured, stored , packaged, labeled, supplied and delivered or shipped (as applicable) in accordance with all applicable international, federal, state and local laws and all executive orders and rules and regulation issued thereunder (collectively, "Applicable Law"). Supplier has obtained and will maintain during the term, all applicable regulatory approvals, applications, licenses, and requests for exemptions, permits or other regulatory authorizations with the applicable regulatory agency. Supplier warrants and represents that it will fulfil all its obligations under this Agreement, and the foregoing warranties and all other warranties express or implied, shall survive shipment, delivery, and payment.<br /></p>
    
        <h6>14.	Indemnification and Liability.</h6>
 	<p>The Supplier shall at all times indemnify, defend, and hold harmless Tweebaa against all claims, actions, damages, losses, liabilities, and expenses, including reasonable outside attorneys' fees, arising out of or caused by any breach of any of the representations, undertakings, or agreements made by the Supplier in connection with:<br /></p>
     	<p>a.any claim of breach of any express or implied warranty or negligence or strict liability, product liability, or similar theory in connection with the production, design, sale, or use of any of the Products purchased by the Buyer;<br /></p>
         	<p>b.any claims of patent or trademark infringement, or other violation of intellectual property rights, of third persons in connection with the production, design, sale, or use of any of the Products purchased by Tweebaa hereunder or the use of the trademarks, trade names, logos, or other intellectual property pertaining thereto; and<br /></p>
             	<p>c.any and all other claims and liabilities of every kind or character whatsoever arising out of, or related to, the production, design, sale, or use of the Products purchased by Tweebaa hereunder, unless the same resulted solely from the Buyer's gross negligence or knowing violation of law.<br /></p>
    
    
    
    
    
    
        <h6>15.	Insurance.</h6>
 	<p>Supplier will add Tweebaa as an "additional insured" under the applicable insurance policies, and will carry and maintain insurance coverage that is sufficient to cover the Supplier's obligation to this Agreement.<br /></p>
    
        <h6>16.	Waiver; Severability.</h6>
 	<p>Whenever possible, each provision of this Agreement will be interpreted in such manner as to be effective and valid under applicable law, but if any provision of this Agreement is held to be invalid, illegal, or unenforceable in any respect under any applicable law or rule in any jurisdiction, such invalidity, illegality, or unenforceability will not affect any other provision or any other jurisdiction, but this Agreement will be reformed, construed, and enforced in such jurisdiction as if such invalid, illegal, or unenforceable provisions had never been contained herein. Any waiver to this Agreement must be in writing and signed by both parties .<br /></p>
    
            <h6>17.	Assignment.</h6>
 	<p>All references in this Agreement to the Parties shall be deemed to include, as applicable, a reference to their respective successors and assigns. The provisions of this Agreement shall be binding on and shall inure to the benefit of the successors and assigns of the Parties. Supplier may not assign any rights or obligations under this Agreement without the prior written consent of Tweebaa. Tweebaa may assign these Terms and Conditions and the Agreement to a present or future affiliate or pursuant to a merger, consolidation, reorganization or sale of all or substantially all of the assets or business to which these Terms and Conditions and the Agreement relate without notice to Supplier.<br /></p>
    
            <h6>18.	Governing Law.</h6>
 	<p>This Agreement shall be governed by the laws of the State of Florida. If litigation results from or arises out of this Agreement or the performance thereof, the Parties agree to reimburse the prevailing Party's reasonable attorneys' fees, court costs, and all other expenses, whether or not taxable by the court as costs, in addition to any other relief to which the prevailing Party may be entitled.
<br /></p>
    
            <h6>19.	Entire Agreement.</h6>
 	<p>This Agreement constitutes the final, complete, and exclusive statement of the Agreement of the Parties with respect to the subject matter hereof, and supersedes any and all other prior and contemporaneous agreements and understandings, both written and oral, between the Parties.<br /></p><br /><br />
						</div><!--about end-->
					</div>
				</div><!--dv_scroll end-->
				<div id="dv_scroll_bar">
					<div id="dv_scroll_track" class="Scrollbar-Track">
						<div class="Scrollbar-Handle"></div>
						<span class="Scrollbar-Handle-blue"></span>
					</div>
				</div>
			</div>
            
            <br />




             <div align="center"><input type="checkbox" disabled="disabled" class="checkbox"  id="readme" onclick="agreeonProtocol();">
          <label for="protocol">我已阅读并同意</label><span class="time"></span>秒</div> <br />
            
            
            
			<div class="tc">
				<a href="#" class="iagree">I Agree</a>
			</div>
            
           <br /> <br />
		</div>
        
        <script>
   $(document).ready(function(){
	   var t=10
    var tt=setInterval(function(){
		$("input[type='checkbox']").removeAttr('disabled')
		$('.time').html(t)
		t--
		if(t==0){
			clearInterval(tt)
		}
		
		},1000)
		
	   });
</script>   
        
	</div> 
</div>
</div>
</asp:Content>
