<%@ Page Title=""  Language="C#" MasterPageFile="~/MasterPages/Main.Master" AutoEventWireup="true" CodeBehind="General_Terms_ofUse.aspx.cs" Inherits="TweebaaWebApp2.College.General_Terms_ofUse" %>
<asp:Content ID="Content1" ContentPlaceHolderID="WebTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="WebCssAndJs" runat="server">
 
    <link rel="stylesheet" href="/css/pages/page_faq1.css">
    <link rel="stylesheet" href="/css/pages/pricing/pricing_v5.css"> 
    <link rel="stylesheet" href="/css/pages/pricing/pricing_v6.css"> 
    <link rel="stylesheet" href="/css/pages/pricing/pricing_v7.css"> 

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="WebContent" runat="server">
 <!--=== Breadcrumbs ===-->
    <div class="breadcrumbs">
        <div class="container">
            <h1 class="pull-left"> General Terms of Service For Tweebaa</h1>
            <ul class="pull-right breadcrumb">
                <li><a href="/index.aspx">Home</a></li>
                <li><a href="#">Pages</a></li>
                <li class="active">Terms of Service</li>
            </ul>
        </div>
    </div><!--/breadcrumbs-->
    <!--=== End Breadcrumbs ===-->
      <!--=== Content Part ===-->
    <div class="container content">		
    	<div class="row-fluid privacy">
    <p>The website operated at <a href="/index.aspx">www.tweebaa.com</a> and such other locations as made available from time to time (collectively, the <strong> “Website”</strong>) and the services offered therefrom (collectively, the  <strong> “Service” </strong>) are operated by Tweeba Inc. and its corporate affiliates (collectively,  <strong> “us”</strong>,  <strong> “we”</strong> or the  <strong> “Tweebaa Companies”</strong>).<br/><br/>
<strong>These terms of service set forth the general terms and conditions of your use of the Website and our Services and are in addition to (not in lieu of) any other terms of use posted on Tweebaa.com and linked from our Terms and Conditions page at Terms and Conditions, which together constitute the entire Agreement (the “Agreement”) between us and you (“you”). By accessing or using the Service, you (together with all persons accessing or using the Service, collectively, the “Users”) signify that you have read, understand and agree to be bound by this Agreement in all respects with respect to the Website, our provision of the Service, and your use of them. <br/><br/>

PLEASE READ THIS AGREEMENT CAREFULLY AS IT CONTAINS IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES AND OBLIGATIONS. THESE INCLUDE, BUT ARE NOT LIMITED TO, VARIOUS LIMITATIONS AND EXCLUSIONS, AND INDEMNITIES.
 </strong>
 </p>
 <ol> <li> <strong>Amendments. </strong> We reserve the right, at our sole discretion, to change, modify, add, or delete portions of this Agreement from time to time without further notice. If we do this, we will notify you by email (if you have registered for a Tweebaa User Account, as defined below) and post the latest version of this Agreement on this page at Terms and Conditions, and we will indicate at the bottom of such page the date of the last revision or modification. Your continued use of the Service, which includes any Tweebaa User Account activity or activities covered by our TweeBuck Activity policy  <a href="/College/TweeBuck.aspx">[TweekBuck link]</a>, after any such change, modification, addition or deletion constitutes your acceptance of the Agreement as then revised. If you do not agree to abide by this or any future version of the Agreement, do not use or access (or continue to use or access) the Service. It is your responsibility to regularly check this page to determine if there have been changes to this Agreement and to review such changes. </li><br />

 
 
 <li> <strong>	Registration Data; Account Security.  </strong>In consideration of your use of the Service, you agree to: (a) provide us with accurate, current and complete information about you as may be prompted by any registration forms on the Service (“<strong>Registration Data</strong>”); and (b) maintain and promptly update the Registration Data, and any other information you provide to us, to keep it accurate, current and complete.  We reserve the right to reject any registration form in our sole discretion. You must be at least 18 years old to register as a User. By providing Registration Data, you signify that you are at least 18 years old and acknowledge that you may not use the Services if you are under the age of 18. If necessary, we may ask you for proof of your age. If you are unable to provide proof of your age, we reserve the right, if our sole discretion, to halt your registration. Individuals under the age of 18 must at all times use the Services on in conjunction with and under the supervision of a parent or legal guardian who is at least 18 years of age. In all cases, the adult is the user and is responsible for any and all activities. Upon providing Registration Data to us through the Service, you will have Service account information (your “<strong>Tweebaa User Account</strong>”). You hereby agree that you will create only one Tweebaa User Account for your use and that you will not transfer or sell your Tweebaa User Account to another party. You may register on behalf of a corporate entity; however you acknowledge and agree that by providing Registration Data in such a capacity, you signify that you are authorized to enter into these terms on behalf of and bind the entity to these terms and to register for the Service. You hereby agree to be fully responsible for (w) all use of your Tweebaa User Account, (x) any action that takes place using your Tweebaa User Account by any person or automated process, (y) maintaining the confidentiality and security of the password to your Tweebaa User Account, and (z) immediately notifying us upon any unauthorized use of your password or your Tweebaa User Account. </li><br />
 
 <li> <strong>Deleting Your Tweebaa User Account;</strong> Inactivity and Deactivation.  You may delete your Tweebaa User Account at any time. All provisions of the Agreement that by their nature are intended to survive, including but not limited to disclaimers of warranties, limitation of liability provisions, and provisions setting out indemnities, governing law, and dispute resolution, will survive termination of your Tweebaa User Account. You further acknowledge that you have read, understand and will be bound by the provisions regarding termination of your Tweebaa User Account in the TweeBucks Activities Terms of Use. You acknowledge that by deleting your Tweebaa User Account, you agree that as of the date of your termination, you will not continue to accrue any rights, Reward Points, Commission, compensation, discounts, cash, TweeBucks, or otherwise on any TweeBuck Activity conducted prior to the date of termination. You understand and agree that you must redeem any TweeBucks available in your Tweebaa User Account before you terminate or delete  your Tweebaa User Account and that these will no longer be available to you as of the date of termination. You further agree that by deleting your Tweeba User Account, you have affirmatively chosen to surrender any Reward Points, TweeBucks, and rights relating to TweeBuck Activity as of the date of termination, regardless of reactivation. If you wish to reactivate your Tweebaa User Account, please contact Tweebaa customer service at services@tweebaa.com. You acknowledge and understand that you must log in to your Tweebaa User Account a minimum of once every 18 months. If you fail to log in to your Tweebaa User Account at least once in each 18 month period, we reserve the right to deactivate your Tweebaa User Account, cancel all prior Product Submissions, and delete all Evaluation history and any related TweeBuck Activity. We also reserve the right to suspend or deactivate your Tweebaa User Account [and retain all or any funds in your Tweebaa User Account] if we suspect or determine, in our sole discretion, that you have used our Services to violate any law or have breached any term of this Agreement. Upon such deactivation, you agree to immediately cease all use of our Services and any Service Content or Content licensed to you in Section 7 of this Agreement. </li><br />
 
 
 <li> <strong>Content. </strong> In this Agreement, “Content” means all materials and content of any type, including, but not limited to, photos, graphics, images, designs, profiles, messages, information, notes, text, information (including Registration Data), comments, survey responses, voting, survey answers, feedback, product descriptions, testimonials, music, sound, video, articles, and software. </li><br />
 
 <li> <strong>User Content and Your License to Us.  </strong>  The Service permits you (or any person using your Tweebaa User Account) to submit, transmit, copy, make available and distribute Content (collectively, your “User Content”), and we do not claim ownership over any User Content.  By providing any User Content, you</li>
<ol class="lower-alpha">
<li>acknowledge that the Tweebaa Companies reserve the right (but not the obligation) to refuse to accept, display, or transmit any User Content in their sole discretion,</li>
<li>	acknowledge that all User Content you submit is public and will not be confidential and as such your submission may affect the ability of you or any other person to obtain or protect trade secret, patent or similar intellectual property rights in the User Content in the future,</li>
<li> grant the Tweebaa Companies the worldwide, royalty-free, sublicensable, non-exclusive right and license to use, distribute, reproduce, modify, adapt, edit, reformat, excerpt, delete, translate, perform and display such User Content as permitted by the functionality of the Service (the “User License”) on the following terms:</li>
<ol class="lower-greek">
<li>acknowledge that the Tweebaa Companies reserve the right (but not the obligation) to refuse to accept, display, or transmit any User Content in their sole discretion,</li>
<li>	acknowledge that all User Content you submit is public and will not be confidential and as such your submission may affect the ability of you or any other person to obtain or protect trade secret, patent or similar intellectual property rights in the User Content in the future,</li>
<li> grant the Tweebaa Companies the worldwide, royalty-free, sublicensable, non-exclusive right and license to use, distribute, reproduce, modify, adapt, edit, reformat, excerpt, delete, translate, perform and display such User Content as permitted by the functionality of the Service (the “User License”) on the following terms:</li>
<ol class="lower-roman">
<li>the User License is limited to the purpose of offering the Service,</li>
<li>the User License includes the Tweebaa Companies’ right to sublicense to third party service providers for the sole purpose of offering the Service, at all times in accordance with this Agreement, and</li>
<li>the User License will end, and the Tweebaa Companies will cease to use User Content, a commercially reasonable period after such User Content is removed from the Service where the Service permits removal and if no removal is permitted, the User License is perpetual, </li>

</ol>
<li>represent and warrant to us that there are no royalties or other amounts owed to any person or entity based on your User Content, and,</li>
<li>represent and warrant to us that (1) you have all right, title and interest to grant the User License, (2) the User Content does not infringe on any other person’s copyright, trade-mark, proprietary interests, trade secrets, privacy or other intellectual property rights, (3) no User Content contains any libellous, defamatory or otherwise unlawful material, and (4) if the submission of User Content may result in a loss in the ability to obtain patent protection over the User Content in the future that you understand the consequences of posting it.</li>
</ol></ol><br/>
 <li> <strong>	Service Content. </strong> All Content available or stored on the Service other than your User Content, including the Service itself, all other Users' Content, any Content made available by the Tweebaa Companies or any third party, and the selection and arrangement of all such Content and User Content (collectively, the “<strong>	Service Content </strong> ”), is the proprietary property of us, the Users or our licensors with all rights reserved, and the Tweebaa Companies (or, as applicable, our Users or licensors) retain and shall retain all right, interest and title in and to all Service Content. </li><br/>
 
  <li> <strong>Our License to You.</strong>   Provided that you are eligible for use of the Service, and that you agree to this Agreement, we hereby grant you a limited, personal, non-transferable, revocable (at any time with or without notice or cause) and non-exclusive right and license to access and use the Service and to download or print a copy of any portion of the Service Content solely for your personal, non-commercial use, and for such uses expressly permitted by this Agreement, subject to this Agreement and provided that you keep all copyright or other proprietary notices intact. You agree to respect all copyright and other legal notices, information, and restrictions contained in any content accessed through tweebaa.com. You further agree not to change, translate, or otherwise create any derivative works of the Services. If we revoke our license to you, you agree to remove any Content infringing the terms of this Agreement and that the terms of the Agreement will survive such revocation and continue to bind you.</li><br/>
  
   <li> <strong>	User Conduct (Things You Must Not Do).  </strong>You acknowledge and agree that the Service is available for your personal, non-commercial use, except explained in the TweeBucks Activities Terms of Use [TweeBucks link]. Without restricting anything else in this Agreement, you agree not to </li><br/>
   <ol class="lower-alpha">
<li>alter, modify, copy, distribute, frame, reproduce, republish, download, display, post, transmit, or sell in any form or by any means, in whole or in part, Service Content, except for Sharing expressly permitted hereby,</li>
<li>except to the extent required to be permitted by the law of your jurisdiction, reverse engineer, decompile, or disassemble, translate or otherwise attempt to extract the source code from the Service, the Service Content, or any part thereof,</li>
<li>make the Service or Service Content available to anyone, or permit anyone to access same, nor license, sublicense, sell, resell, publish, republish, transfer, assign, distribute, rent, lease, time-share, copy or otherwise commercially exploit the Service in any way except in furtherance of your permitted use in accordance with this Agreement,</li>
<li>republish any Service Content on any Internet, Intranet or Extranet site (except for Sharing expressly permitted hereby) or incorporate the information in any other database or compilation, without our prior written permission or the permission of the particular Content owner, as the case may be,</li>
<li>use any data mining, robot or similar data gathering or extraction methods with respect to any Service or any Service Content,</li>
<li>register for more than one Tweebaa User Account (except as provided herein), register for a Tweebaa User Account on behalf of an individual other than yourself (except if you are the parent or legal guardian to such individual), or register for a Tweebaa User Account on behalf of any group or non-individual entity (except if you are duly authorized to do so by such group or entity),</li>
<li>impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with any person or entity, in your Registration Data, Tweebaa User Account or otherwise;</li>
<li>upload, post, transmit, share or otherwise make available on the Service any User Content that </li>

<ol class="lower-greek">
<li>consists of any unsolicited or unauthorized advertising, solicitations, promotional materials, “junk mail,” “spam,” “chain letters,” “pyramid schemes,” or any other form of solicitation, or</li>
<li>contains any private information of any third party, including, without limitation, addresses, phone numbers, email addresses, Social Insurance Numbers, US Social Security numbers, credit card numbers, financial information and other personally identifying or private information, unless that third party has consented to such use of its private information,</li>
<li>in our sole discretion, is harmful, threatening, unlawful, defamatory, libelous, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable,</li>
<li>is a counterfeit or stolen item,</li>
<li>impersonates or intimidate any person (including Tweebaa staff or other Users), or falsely states or otherwise misrepresent your affiliation with any person, through for example, the use of similar email address, nicknames, or creation of false account(s) or any other method or device, </li>
<li>	violates any applicable law, statute, ordinance or regulation including but not limited to those governing export control, consumer protection, unfair competition, anti-discrimination, or false advertising,</li>
<li>	contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, or</li>
<li>	would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law,</li>

</ol>
<li>disable or circumvent any access control or related process or procedure established with respect to the Service, or attempt to gain unauthorized access to the Service or Service Content, </li>
<li>remove any copyright or other proprietary notices on or in the Service, Service Content or any part thereof, </li>
<li>solicit personal information from anyone under 18 or solicit passwords or personally identifying information from any person for commercial or unlawful purposes, </li>
<li>use the Service or any Service Content to “stalk”, intimidate, harm or otherwise harass another User or another person,</li>
<li>intentionally or unintentionally violate any applicable local, state, national or international law, including any regulations thereto, or any court order or lawful order of any governmental authority, </li>
<li>access the Service in order to (i) build a competitive product or service, or (ii) copy any features, functions or graphics of the Service or Service Content,</li>
<li>utilize the Service in any way except as expressly permitted by this Agreement, including by developing or using any software tool or other application that interfaces with the Service or the Website except for standard web browsers, </li>
<li>interfere with or disrupt the Service or Service Content (including the servers, networks or technology connected to the Service), or</li>
<li>use or attempt to use another's Tweebaa User Account or the Service without express authorization from us or the applicable User.</li>
</ol><br />
   <li> <strong>	Nudity and Objectionable Material.</strong>  You acknowledge and agree that the Service must remain a safe site for families with children, so you agree not to, and we strictly prohibit, the uploading and display of any User Content portraying explicit nudity, adult content, or that is unacceptable for viewing by minors or objectionable, in our sole discretion. For example, but without limitation, prohibited User Content would include material that would be unacceptable in a public museum where minors visit, or User Content that would only be appropriate for adult sites, adult magazines, or R-rated movies. You acknowledge and agree that the sole discretion of whether User Content is suitable belongs to us, and we reserve the right (but have no obligation) to (a) delete any User Content we deem to violate this Agreement or, or (b) to cancel the Tweebaa User Account from which such User Content made available on the Service.</li><br/>
  <li> <strong>User Content Responsibility.</strong> You acknowledge and agree that (a) you are solely responsible for all of your User Content, and (b) we may, but are not obligated to, review and delete or remove (without notice) any User Content, in our sole discretion, including, without limitation, any User Content that violates this Agreement. You agree that you must evaluate, and bear all risks associated with, the use of any User Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not rely on any Service Content (except for this Agreement, the Privacy Policy and other legally binding agreements) for any purpose whatsoever.  You will also comply with any of your own local laws regarding online conduct and acceptable content, including laws relating to the export of data if you are outside of Canada.</li><br/>
<li> <strong>Other Uses. </strong> Any use of the Service or the Service Content other than as specifically authorized in this Agreement, without our prior written permission, is strictly prohibited and will automatically terminate all licenses granted by us herein. Such unauthorized use may also violate applicable laws including, without limitation, copyright, privacy, trade-secrets and trademark laws and applicable communications regulations and statutes. Unless explicitly stated herein, nothing in this Agreement shall be construed as conferring any other license to intellectual property rights, whether by estoppel, implication or otherwise.</li><br/>
<li> <strong>Trademarks.</strong>  Notwithstanding anything else in this Agreement, “Tweebaa”, the Tweebaa logo and design, and all other trade-marks, trade dress, graphics, logos, designs, page headers, button icons, scripts and service names used by the Tweebaa Companies on or in connection with the Service (collectively, the “<strong>Marks</strong>”) are registered trademarks, trademarks or trade dress of the Tweebaa Companies or our licensors and all right, title and interest in and to the Marks, whether registered or not, are and shall remain vested in us or in our licensors, as applicable. The Marks may not be used, including as part of trademarks, trade names, trade dress or as part of domain names, in connection with any product or service in any manner that is likely to cause confusion and may not be copied, imitated, or used, in whole or in part, without our prior written permission..</li><br/>    
<li> <strong>Third Party Sites and Content.</strong>  The Service may contain (or you may be presented with through the Service) links to Third Party Sites as well as Content belonging to or originating from parties other than us or our Users (the “<strong>Third Party Content</strong>”). Such Third Party Sites and Third Party Content are not investigated, monitored or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third Party Sites accessed through the Service or any Third Party Content available on the Service, including, without limitation, the content, accuracy, offensiveness, opinions, reliability or policies of or contained in the Third Party Sites or the Third Party Content. The inclusion of or linking to any Third Party Site or any Third Party Content does not imply approval or endorsement thereof by us. If you access the Third Party Sites whether directly with the Third Party Site or indirectly through the Service, you do so at your own risk and you acknowledge and agree that our terms and policies do not govern same and that we have no liability arising from your use of or access to any Third Party Site or Third Party Content. You should review the applicable terms and policies, including privacy and data gathering practices, of any Third Party Site to which you navigate from the Service. Reference on the Service to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise, does not constitute or imply (a) endorsement, sponsorship or recommendation thereof by, or (b) or any affiliation thereof with the Tweebaa Companies.</li><br/>    
<li> <strong>Modifications to Service. </strong> We reserve the right at any time and from time to time to perform maintenance on, to add to, to remove from, to make upgrades and updates to, to suspend, and to modify the Service or any part thereof with or without notice. NOTWITHSTANDING ANY PROVISION HEREIN, YOU AGREE THAT WE SHALL NOT BE LIABLE IN ANY MANNER TO YOU OR TO ANY THIRD PARTY FOR ANY SUCH MAINTENANCE, ADDITION, REMOVAL, UPGRADE, UPDATE, SUSPENSION OR MODIFICATION.</li><br/>    
<li> <strong>Advertisements. </strong> We may run advertisements and promotions on the Service. You agree that we have the right to run such advertisements and promotions nothwithstanding any User Content you provide. The manner, mode and extent of advertising by us on the Service is subject to change in our sole discretion. </li><br/> 

<li> <strong>General Practices regarding Use and Storage. </strong> You acknowledge that we may establish general practices and limits concerning use of the Service, including, without limitation, the maximum number of days that User Content will be retained by the Service, the maximum number of User Content that may be transmitted, posted, shared, used, copied, or otherwise made available on the Service (whether per Tweebaa User Account or globally), the maximum size of any User Content, the maximum disk space that will be allotted on the Service servers on any User's behalf, and the maximum number of times (and the maximum duration for which) any User may access the Service in a given period of time. You agree that we have no responsibility or liability for the deletion or failure to store any User Content and other communications or Content maintained or transmitted by the Service. You acknowledge that we reserve the right to log off or otherwise disconnect any Tweebaa User Account that is inactive for a period of 18 months or such other extended period of time in our sole discretion.</li><br/> 

<li> <strong>User-and-User Disputes.  </strong> You are solely responsible for your interactions with other Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users and to take any action with respect to any Tweebaa User Account pertaining to such Users, in our sole discretion.</li><br/> 

<li> <strong>Disclaimers. </strong> </li><br/> 
 <ol class="lower-alpha">
<li><strong>No Responsibility for Others’ Content.</strong>  We are not responsible or liable in any manner for any User Content or Third Party Content available on the Service, whether made available or caused to be made available by Users or by any of the technology associated with or utilized in the Service. Although we provide this Agreement and other policies and rules for User conduct, we do not control and are not responsible for our Users’ actions and are not responsible for any Content you may encounter on the Service, be it User Content or Third Party Content. We are not responsible for the conduct, whether online or offline, of any User.  Notwithstanding anything else in this Agreement, the Tweebaa Companies have no responsibility to monitor any User Content or Third Party Content.</li>
<li><strong>Availability. </strong> The Service may be temporarily unavailable from time to time for maintenance or other reasons. We assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, User Content. We are not responsible for any problems or technical malfunction, including, without limitation, any problem or malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of email or persons, traffic congestion on the Internet or at any web site (including the those in the Service) or combination thereof.</li>
<li><strong>AS IS; AS AVAILABLE. </strong> THE SERVICE AND THE SERVICE CONTENT ARE PROVIDED “AS IS” AND “AS AVAILABLE” AND THE TWEEBAA COMPANIES DISCLAIM ANY AND ALL REPRESENTATIONS AND WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. THE TWEEBAA COMPANIES CANNOT GUARANTEE AND DO NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SERVICE. THE TWEEBAA COMPANIES DO NOT REPRESENT OR WARRANT THAT THE SERVICE CONTENT IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE, OR THAT THE SERVICE IS FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THEREFORE, YOU SHOULD EXERCISE CAUTION IN THE USE AND DOWNLOADING OF ANY SUCH CONTENT AND USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES. THE TWEEBAA COMPANIES DISCLAIM ANY AND ALL RESPONSIBILITY FOR ANY THIRD PARTY CONTENT OR THIRD PARTY SITES.</li><br/>

</ol>

<li> <strong>Limitation on Liability.</strong>  EXCEPT IN JURISDICTIONS WHERE SUCH PROVISIONS ARE RESTRICTED (AND, THEN, ONLY TO THE STRICT EXTENT OF SUCH RESTRICTION), IN NO EVENT WILL THE TWEEBAA COMPANIES, OR THEIR DIRECTORS, PARTNERS, OFFICERS, EMPLOYEES, CONTRACTORS OR AGENTS, BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, AND WHETHER DIRECT OR INDIRECT, FOR ANY LOST PROFITS, LOST BUSINESS OPPORTUNITIES, OR LOST DATA, ARISING FROM YOUR USE OF THE SERVICE, THE SERVICE CONTENT OR OTHER MATERIALS ON OR ACCESSED THROUGH THE SERVICE (INCLUDING ALL THIRD PARTY CONTENT AND THIRD PARTY SITES), EVEN IF THE TWEEBAA COMPANIES ARE AWARE OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, THE TWEEBAA COMPANIES' LIABILITY TO YOU FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) THE AMOUNT PAID, IF ANY, BY YOU TO THE TWEEBAA COMPANIES FOR THE SERVICE DURING YEAR IN WHICH YOUR SUCH CAUSE AROSE, OR (B) THE VALUE OF TWEEBUCKS THEN HELD BY YOU OR COVERED BY YOU STRICTLY AS CALCULATED PER THIS AGREEMENT, BUT IN NO CASE (REGARDLESS OF WHICH OF (A)OR (B) IS GREATER) WILL THE TWEEBAA COMPANIES' LIABILITY TO YOU EXCEED $100.00. YOU ACKNOWLEDGE THAT IF NO SUCH AMOUNTS ARE PAID BY YOU TO THE TWEEBAA COMPANIES FOR THE SERVICE, YOU SHALL BE LIMITED TO INJUNCTIVE RELIEF ONLY, UNLESS OTHERWISE PERMITTED BY LAW, AND SHALL NOT BE ENTITLED TO DAMAGES OF ANY KIND FROM THE TWEEBAA COMPANIES, REGARDLESS OF THE CAUSE OF ACTION.  CERTAIN JURISDICTIONS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS BUT ONLY TO THE EXTENT OF SUCH EXCLUSION BY APPLICABLE LAW. NOTHING IN THIS AGREEMENT IS INTENDED TO EXCLUDE OR LIMIT ANY CONDITION, WARRANTY, RIGHT OR LIABILITY THAT MAY NOT BE LAWFULLY EXCLUDED OR LIMITED. IF YOU ARE IN A JURISDICTION THAT DOES NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY OR CERTAIN CATEGORIES OF DAMAGES, YOU AGREE THAT OUR LIABILITY, IF ANY, WILL BE LIMITED TO THE FULLEST EXTENT PERMITTED BY SUCH JURISDICTION.</li><br/>

<li> <strong>Privacy.  </strong> 	We care about the privacy of our Users. You can view our privacy policy at <a href="#">*[PRIVACY POLICY LINK].  </a>Without limiting that, you acknowledge that we may (but have no obligation to) access, preserve and disclose your Tweebaa User Account data and any User Content if, in good faith, we believe that same is reasonably needed to (a) comply with applicable law or legal process, (b) enforce this Agreement, (c) protect against imminent harm to any person, any safety of any person, or any property of any person, or (d) such access, preservation, or disclosure is permitted under applicable law.  You further acknowledge that the Service uses the Internet and other, third-party networks, and that, accordingly, any information processed using the Service may be processed or transmitted over various networks (including those outside of our control). </li><br/>
<li> <strong>Copyright, Intellectual Property and Content Complaints.  </strong>If you believe that any Content on the Service infringes upon any copyright or other intellectual property right that you own or control, or if you otherwise object to any User Content that you find on the Service, you may send a written notification as follows<br /><br />
by e-mail: *[services@tweebaa.com]<br />
by regular mail: Tweebaa Inc.<br />
                          HSBC Tower Suite 302 <br />
                          3601 Highway 7 East<br />
                          Markham, Ontario<br />
                          L3R OM3, Canada<br />
The notification must be a written communication that includes the following:
 </li><br/>
 <ol class="lower-alpha">
<li>a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
<li>if the complaint is about copyright or other intellectual property rights, identification of the copyrighted work or other intellectual property right claimed to have been infringed, or, if multiple infringements are covered by a single notification, a representative list of such infringements;</li>
<li>if the complaint is about objectionable content, the reasons for the objection;</li>
<li>identification of the material that you are objecting to and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material;</li>
<li>information reasonably sufficient to permit us to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address at which the complaining party may be contacted;</li>
<li>a statement that the information in the notification is accurate; and</li>
<li>if the complaint is about copyright or other intellectual property rights, a statement under penalty of perjury, that (i) the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed, and (ii) the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the owner thereof, its agent or the law.</li><br/></ol>


<li> <strong>Abuser and Repeat Abuser Policy.  </strong>  We have adopted a policy of terminating, in appropriate circumstances and at our sole discretion, members who are deemed to be repeat infringers of intellectual property or users or posters of objectionable content. We may also, at our sole discretion, limit access to the Service or terminate the Tweebaa User Account of any User who infringes any intellectual property rights of us or others, whether or not there is any repeat infringement, or otherwise uses or posts objectionable content through the Service.</li><br/>


<li> <strong>Governing Law; Venue and Jurisdiction.   </strong>  You agree that the laws of the Province of Ontario, Canada, without regard to principles of conflict of laws will govern this Agreement and any dispute of any sort that might arise between you and us. You hereby irrevocably attorn to the exclusive jurisdiction of the Courts of the Province of Ontario with respect to any dispute hereunder. </li><br/>
<li> <strong> Dispute Resolution.   </strong> </li>

<ol class="lower-alpha">
<li><strong>Contact Us First.  </strong> We care about addressing your concerns in an informal and efficient manner.  For any dispute you have with us regarding the Services, you agree to first contact us and attempt in good faith to resolve the dispute informally by reporting the dispute to our customer service online at any time by emailing<strong>services@tweebaa.com. </strong>You agree that if our dispute is not resolved by informal resolution within 15 days of your submission, you will resolve any claims through final and binding arbitration (<strong>“Arbitration”</strong>).</li>
<li><strong>Arbitration.  </strong> IMPORTANT NOTICE ABOUT YOUR RIGHTS – PLEASE READ  <a href="Arbitration_agreement.aspx">Arbitration Agreement. </a></li>
<li><strong>No Class Actions. </strong> You hereby agree and acknowledge that you may only resolve disputes with us on an individual basis, and may not bring a claim as a plaintiff or a class member in a class, purported class, consolidated, or representative action. You further agree that, by entering into these terms, you and the Tweebaa Companies each agree that all claims and disputes shall be resolved under this Agreement. You further waive any constitutional or statutory right to go to court and have a trial in front of a judge or jury on an individual, class action, or representative action basis. In the event any litigation should arise between you and us, in any jurisdiction, in a suit to vacate or enforce an Arbitration award or otherwise, you and the Tweebaa Companies waive all rights to a jury trial, instead electing that the dispute be resolved by a judge, and agree to take any and all action necessary or appropriate to effect such waiver.</li>
<li><strong>Statute of Limitations. </strong> You hereby agree that any claim under this Agreement must be brought within one year of the act giving rise to the claim. </li>

</ol><br/>
<li> <strong>Indemnity. </strong> You hereby agree to indemnify and hold the Tweebaa Companies and each of their directors, officers, agents, contractors, partners and employees, harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney's fees, arising out of or in connection with any User Content and any Third Party Content, your use of the Service, your conduct in connection with the Service or with other Users of the Service, or any violation of (a) this Agreement, (b) any law, or (c) any right of any third party.   </li>

<li> <strong>Submissions.</strong> Notwithstanding any term herein related to User Content, you acknowledge and agree that any questions, comments, suggestions, ideas, feedback or other information about the Website or Service (collectively, “Submissions”), provided by you to us are non-confidential and shall become the sole property of the Tweebaa Companies, who shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination thereof for any purpose, commercial or otherwise, without acknowledgment or compensation to you. </li><br/>
<li> <strong>Electronic Communications. </strong> When you use the Service or send e-mails to us, or register for a Tweebaa User Account, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail to the email address attached to your Tweebaa User Account through your Registration Data or by posting notices on (a) the Service at-large, or (b) into your personal message centre available on the Service. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. </li><br/>

<li> <strong>Merger or Acquisition. </strong> It is possible that any of the Tweebaa Companies may be acquired or transferred as part of a merger, acquisition or other change of control. In the event of such a transaction, you understand and agree that we may assign our rights under this Agreement and that your personal information may be transferred to the succeeding entity in accordance with our Privacy Policy. You will be provided with reasonable notice and an opportunity to opt-out of the transfer. </li><br/>
<li> <strong>Interpretation.</strong> Headings are for convenience only and shall not be used to interpret, or as a guide for interpretation of, this Agreement. The word “or” is not exclusive and the word “including” is not limiting (whether or not non-limiting language such as “without limitation” or “but not limited to” or other words of similar import are used with reference thereto). A word importing the masculine gender includes the feminine and neuter, a word in the singular includes the plural, a word importing a corporate entity includes an individual, and vice versa and “person” will mean an individual, partnership, corporation (including a business trust), joint stock company, trust unincorporated association, joint venture, or other entity or a government or any agency, department or instrumentality thereof and vice versa.</li><br/>

<li> <strong>Other. </strong> This Agreement constitute the entire agreement between you and us regarding the use of the Service, superseding any prior agreements between you and us relating to your use of the Site or the Service. Our failure to exercise or enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision in that or any other instance. If any provision of this Agreement is held invalid, unlawful, void or unenforceable for any reason, that provision shall be deemed severable and the remainder of this Agreement shall continue in full force and effect. This Agreement shall enure to the benefit of, and be binding upon, parties hereto and their respective heirs, executors, administrators, successors, and assigns.</li><br/>
<li> <strong>English Language. </strong>The parties have requested and agree that this Agreement and all documents relating thereto be drawn up in English.  Les parties ont demandé que cette convention ainsi que tous les documents qui s’y rattachent soinet rédigés en anglais.
<br /><br />
End of Terms of Service (Last Updated: 06/06/15)<br /><br />
</li>
</ol></div></div>
        <!--=== Content Part ===-->

</asp:Content>
