                        <a onclick="javascript:void(0);" target="_blank" id="shareToFacebook" title="Facebook"><img src="../Images/flat-circles_03.png" /></a>&nbsp;&nbsp;
                        <a onclick="javascript:void(0);" target="_blank" id="shareToTwitter" title="Twitter"><img src="../Images/flat-circles_05.png" /></a>&nbsp;&nbsp;
                        <a onclick="javascript:void(0);" target="_blank" id="shareToGoogle" title="Google"><img src="../Images/flat-circles_13.png" /></a>&nbsp;&nbsp;
                        <!--a href="javascript:void(0)" target="_blank" id="share4" title="Wechat"><img src="../Images/share-rss.png" /></a>&nbsp;&nbsp;-->
                        <a onclick="javascript:void(0);" target="_blank" id="shareToPinterest" title="Pinterest"><img src="../Images/share-pin.png" /></a>&nbsp;&nbsp;
                        <%--<a href="javascript:void(0)" target="_blank" id="share6" title="email"><img src="../Images/flat-circles_03.png" /></a>--%>
                        <a onclick="javascript:void(0)" target="_blank" id="shareToEmail" title="Email"><img src="../Images/share-mail.png" /></a>
